package io.wilder.deckchoice;

import io.wilder.deckchoice.persistence.MetaForecastDb;
import org.skife.jdbi.v2.DBI;
import org.skife.jdbi.v2.Handle;
import org.skife.jdbi.v2.util.StringMapper;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public void getGreeting() {
        String res = createNewDatabase();
        System.out.print(res);
    }

    public static String createNewDatabase() {

        MetaForecastDb.wipeDatabase();
        MetaForecastDb.applySchema();
        DBI dbi = MetaForecastDb.getDbi();
        Handle h = dbi.open();

        h.execute("insert into players (player_id, name) values (?, ?)", 1, "Brian");

        String name = h.createQuery("select name from players where player_id = :id")
                .bind("id", 1)
                .map(StringMapper.FIRST)
                .first();
        System.out.println(name);
        h.close();
        return name;
    }
}
